#### Note:

Make sure that you have these two scripts running at the same time while running this

ark regsitry start

python sim_node.py

In [15]:
import numpy as np
from arktypes import joint_group_command_t, task_space_command_t, joint_state_t
from arktypes.utils import unpack, pack
from ark.client.comm_infrastructure.instance_node import InstanceNode

SIM = True

class FrankaControllerNode(InstanceNode):

    def __init__(self):
        '''
        Initialize the FrankaJointController.
        This class is responsible for controlling the Franka robot's joints.
        '''
        super().__init__("FrankaJointController")

        if SIM == True:
            self.joint_group_command_sim = self.create_publisher("SO100/joint_group_command/sim", joint_group_command_t)
            self.task_space_command_sim = self.create_publisher("SO100/cartesian_command/sim", task_space_command_t)

            self.joint_group_command = self.create_publisher("SO100/joint_group_command", joint_group_command_t)
            self.task_space_command = self.create_publisher("SO100/cartesian_command", task_space_command_t)

            self.state = self.create_listener("SO100/joint_states/sim", joint_state_t)

controller = FrankaControllerNode()

[WARNING] [17:22:55.028180] - No global configuration provided. Using default system configuration.
[INFO] [17:22:55.042665] - Service: Successfully registered '__DEFAULT_SERVICE/GetInfo/FrankaJointController_26b1b3e7-869e-46a9-b8c5-04eaf734e531' with registry.
[INFO] [17:22:55.050348] - Service: Successfully registered '__DEFAULT_SERVICE/SuspendNode/FrankaJointController_26b1b3e7-869e-46a9-b8c5-04eaf734e531' with registry.
[INFO] [17:22:55.062513] - Service: Successfully registered '__DEFAULT_SERVICE/RestartNode/FrankaJointController_26b1b3e7-869e-46a9-b8c5-04eaf734e531' with registry.
[ERROR] [17:22:55.065396] - Couldn't load config for other 'FrankaJointController'
[OK] [17:22:55.073005] - setup publisher SO100/joint_group_command/sim[joint_group_command_t]
[OK] [17:22:55.076377] - setup publisher SO100/cartesian_command/sim[task_space_command_t]
[OK] [17:22:55.077428] - setup publisher SO100/joint_group_command[joint_group_command_t]
[OK] [17:22:55.079212] - setup publisher SO100/c

None


Get info service called
Get info service called
Get info service called
Get info service called
Get info service called
Get info service called
Get info service called
Get info service called
Get info service called


---

# Joint Group Control

In [16]:
joint_command = [1,0,-1,0,0,0]
# Position Control
controller.joint_group_command_sim.publish(pack.joint_group_command(joint_command, "all"))
controller.joint_group_command.publish(pack.joint_group_command(joint_command, "all"))

In [14]:
gripper_command = [-1] # -1 close, 1 open
# Velocity Control 
controller.joint_group_command.publish(pack.joint_group_command(gripper_command, "gripper"))

In [10]:
arm_command = [-0.3, 0.5, 0.3, -1.0, 0.1, 1.8, 0.1]
# Position Control 
controller.joint_group_command.publish(pack.joint_group_command(arm_command, "arm"))

---

# Task Space Control

In [5]:
xyz_command = np.array([0.3, 0.4, 0.8])
quaternion_command = np.array([1, 0.0, 0.0, 0.0]) # xyz-w
gripper = 1.0 # 0.0 close, 1.0 open

controller.task_space_command.publish(
    pack.task_space_command("all", xyz_command, quaternion_command, gripper))

---


# Joint States

In [17]:
unpack.joint_state(controller.state.get())

({'seq': 0, 'stamp': {'sec': 0, 'nsec': 0}, 'frame_id': ''},
 ['shoulder_pan',
  'shoulder_lift',
  'elbow_flex',
  'wrist_flex',
  'wrist_roll',
  'gripper'],
 array([ 9.99999464e-01, -2.94127203e-05, -9.97921526e-01,  1.00760942e-03,
         2.78938774e-06, -4.97423607e-05]),
 array([0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0.]))